---
AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable         # enable new upcoming cops for rubocop
  Exclude:
    - _snippets/**/*

# ignore block length where unavoidable (e.g., framework requires it)
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - Rakefile # Rake namespaces produce large blocks

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude:
    - Rakefile
    - app/db/migrations/*.rb