---
# COPY and this file to secrets.yml and modify as needed
development:
  DATABASE_URL: sqlite://app/db/store/development.db
  DB_KEY: y++QwyTnECSw7axUTXfR0qtV5J98waam3XWkUt7ah8g=
  MSG_KEY: yZVkRBW8s0MM9iNx6uY7ujlR0P1D+ptmcKwcA5Cln+c=
  SENDGRID_APIKEY: <SendGrid API Key>
  SENDGRID_SENDER: <Provisiioned SendGrid Sender Address>
  SECURE_SCHEME: HTTP
  GITHUB_OAUTH_CLIENT_ID: <your_github_oauth_client_id>
  GITHUB_OAUTH_CLIENT_SECRET: <your_github_oauth_client_secret>
  SIGNING_KEY: 3U2+C5g+1oI8ijYr8EFv3NGd7doN7f9KbXM2G8ftmxE=
  VERIFY_KEY: BRTCRPd2lKMjNVr8R88qgmOaEKSFm9cBxil6CL0QJpU=
  REDIS_URL: redis://

test:
  DATABASE_URL: sqlite://app/db/store/test.db
  DB_KEY: y++QwyTnECSw7axUTXfR0qtV5J98waam3XWkUt7ah8g=
  MSG_KEY: yZVkRBW8s0MM9iNx6uY7ujlR0P1D+ptmcKwcA5Cln+c=
  SENDGRID_APIKEY: <SendGrid API Key>
  SENDGRID_SENDER: <Provisiioned SendGrid Sender Address>
  SECURE_SCHEME: HTTP
  GITHUB_OAUTH_CLIENT_ID: <your_github_oauth_client_id>
  GITHUB_OAUTH_CLIENT_SECRET: <your_github_oauth_client_secret>
  SIGNING_KEY: 3U2+C5g+1oI8ijYr8EFv3NGd7doN7f9KbXM2G8ftmxE=
  VERIFY_KEY: BRTCRPd2lKMjNVr8R88qgmOaEKSFm9cBxil6CL0QJpU=
  REDIS_URL: redis://

production:
  DATABASE_URL: <do not set - set directly on production server>
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  MSG_KEY: <use `rake newkey:msg` to generate a secret key>
  SENDGRID_APIKEY: <SendGrid API Key>
  SENDGRID_SENDER: <Provisiioned SendGrid Sender Address>
  SECURE_SCHEME: HTTPS
  GITHUB_OAUTH_CLIENT_ID: <your_github_oauth_client_id>
  GITHUB_OAUTH_CLIENT_SECRET: <your_github_oauth_client_secret>
  SIGNING_KEY: <`rake newkey:signing`> # needed by client app; used in api tests
  VERIFY_KEY: <`rake newkey:signing`>
  REDIS_URL: <do not set - set directly on production server>